// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250121082752_addchiphi")]
    partial class addchiphi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Data.MyDbContext+ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("PhanMem_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TapDoan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ERP.Data.MyDbContext+ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool?>("AccountLevel")
                        .HasColumnType("bit");

                    b.Property<string>("ChucDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuoiPhongBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonViTraLuong_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnhUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustChangePass")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NghiViec")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ERP.Data.MyDbContext+ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Default")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive_Role")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ERP.Models.Adsun", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ACOnOff")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Angle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeginStop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayDrivingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Door")
                        .HasColumnType("bit");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrivingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gps")
                        .HasColumnType("bit");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gsm")
                        .HasColumnType("bit");

                    b.Property<string>("InputPower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverSpeed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStop")
                        .HasColumnType("bit");

                    b.Property<bool>("Key")
                        .HasColumnType("bit");

                    b.Property<string>("Km")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Liciense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Over10h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Over4h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverSpeedCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SheeatsOrTons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopCounter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temper2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripKm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adsuns");
                });

            modelBuilder.Entity("ERP.Models.BoPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoPhan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaBoPhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PhongBan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBoPhan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhongBan_Id");

                    b.ToTable("BoPhans");
                });

            modelBuilder.Entity("ERP.Models.CBNV_DieuChuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DieuChuyenNhanVien_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViTraLuongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViTraLuongNewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViTraLuongNew_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViTraLuong_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DieuChuyenNhanVien_Id");

                    b.HasIndex("DonViTraLuongId");

                    b.HasIndex("DonViTraLuongNewId");

                    b.HasIndex("User_Id");

                    b.ToTable("CBNV_DieuChuyen");
                });

            modelBuilder.Entity("ERP.Models.ChiTiet_DV_PB_BP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoPhan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChucVu_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PhongBan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TapDoan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ChiTiet_DV_PB_BPs");
                });

            modelBuilder.Entity("ERP.Models.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("ERP.Models.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PageSize")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("ERP.Models.DM_BaoDuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiaTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiBaoDuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TanSuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DM_BaoDuongs");
                });

            modelBuilder.Entity("ERP.Models.DM_BoPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaBP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Eng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonVi_Id");

                    b.ToTable("DM_BoPhans");
                });

            modelBuilder.Entity("ERP.Models.DM_DonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaDV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Eng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DM_DonVis");
                });

            modelBuilder.Entity("ERP.Models.DM_Loai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Eng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Nhom_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuocNhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nhom_Id");

                    b.ToTable("DM_Loais");
                });

            modelBuilder.Entity("ERP.Models.DM_Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KLBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KLKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KLTB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Eng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PairingAbility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TTMK_KLHH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DM_Models");
                });

            modelBuilder.Entity("ERP.Models.DM_Nhom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Eng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DM_Nhoms");
                });

            modelBuilder.Entity("ERP.Models.DM_TinhTrang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Arrange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DM_TinhTrangs");
                });

            modelBuilder.Entity("ERP.Models.DS_PhuongTien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address_nearest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BienSo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BienSo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonViSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KLBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KLHH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KLKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KLTB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LoaiPT_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPhuongTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Model_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model_Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoChuyenXe")
                        .HasColumnType("int");

                    b.Property<int>("SoKM")
                        .HasColumnType("int");

                    b.Property<string>("SoKhung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TinhTrang_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri_Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri_Long")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonVi_Id");

                    b.HasIndex("LoaiPT_Id");

                    b.HasIndex("Model_Id");

                    b.HasIndex("TinhTrang_Id");

                    b.ToTable("DS_PhuongTiens");
                });

            modelBuilder.Entity("ERP.Models.DS_ThietBi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiTB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LoaiTB_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCode_BienSo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCode_BienSo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaThietBi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Model_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanBo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiGianSuDung")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri_Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri_Long")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiTB_Id");

                    b.HasIndex("Model_Id");

                    b.ToTable("DS_ThietBis");
                });

            modelBuilder.Entity("ERP.Models.DieuChuyenNhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoPhanNewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoPhanNew_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoPhan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChucVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChucVuNewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChucVuNew_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChucVu_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonViId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViNewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViNew_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaDieuChuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayDieuChuyen")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PhongBanNew_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongbanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongbanNewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TapDoanNew_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TapDoan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("XacNhan")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BoPhanId");

                    b.HasIndex("BoPhanNewId");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("ChucVuNewId");

                    b.HasIndex("DonViId");

                    b.HasIndex("DonViNewId");

                    b.HasIndex("PhongbanId");

                    b.HasIndex("PhongbanNewId");

                    b.HasIndex("User_Id");

                    b.ToTable("DieuChuyenNhanViens");
                });

            modelBuilder.Entity("ERP.Models.DonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaDonVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TapDoan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TapDoan_Id");

                    b.ToTable("DonVis");
                });

            modelBuilder.Entity("ERP.Models.KeHoachBaoDuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaoDuong_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DiaDiem_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsQuaHan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PhuongTien_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ThietBi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaoDuong_Id");

                    b.HasIndex("PhuongTien_Id");

                    b.HasIndex("ThietBi_Id");

                    b.ToTable("KeHoachBaoDuongs");
                });

            modelBuilder.Entity("ERP.Models.LichSuBaoDuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaoDuong_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChiPhi")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DiaDiem_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PhuongTien_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ThietBi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaoDuong_Id");

                    b.HasIndex("PhuongTien_Id");

                    b.HasIndex("ThietBi_Id");

                    b.ToTable("LichSuBaoDuongs");
                });

            modelBuilder.Entity("ERP.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AccessDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AccessdBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccessdBy");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ERP.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonVi_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Parent_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhanMem_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TapDoan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenMenu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("isMoBi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("ERP.Models.Menu_Role", b =>
                {
                    b.Property<Guid>("Menu_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Role_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Add")
                        .HasColumnType("bit");

                    b.Property<bool>("Cof")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Del")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Print")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("View")
                        .HasColumnType("bit");

                    b.HasKey("Menu_Id", "Role_Id");

                    b.HasIndex("Role_Id");

                    b.ToTable("Menu_Roles");
                });

            modelBuilder.Entity("ERP.Models.NhomDoiTac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaNhomDoiTac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNhomDoiTac")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenNhomDoiTac_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NhomDoiTacs");
                });

            modelBuilder.Entity("ERP.Models.Phongban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaPhongBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PhongBan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonVi_Id");

                    b.ToTable("phongbans");
                });

            modelBuilder.Entity("ERP.Models.PhuongTien_DonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoPhan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_To")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PhuongTien_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoPhan_Id");

                    b.HasIndex("DonVi_Id");

                    b.HasIndex("PhuongTien_Id");

                    b.ToTable("PhuongTien_DonVis");
                });

            modelBuilder.Entity("ERP.Models.PhuongTien_PhuTrach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_To")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PhuongTien_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhuongTien_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("PhuongTien_PhuTrachs");
                });

            modelBuilder.Entity("ERP.Models.RoleByDonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("RoleByDonVis");
                });

            modelBuilder.Entity("ERP.Models.Role_DV_PB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoPhan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Phongban_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleByDonVi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TapDoan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BoPhan_Id");

                    b.HasIndex("DonVi_Id");

                    b.HasIndex("Phongban_Id");

                    b.HasIndex("RoleByDonVi_Id");

                    b.HasIndex("TapDoan_Id");

                    b.ToTable("Role_DV_PBs");
                });

            modelBuilder.Entity("ERP.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Statuss");
                });

            modelBuilder.Entity("ERP.Models.TaiXe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HangBang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaTaiXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isVaoCong")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TaiXes");
                });

            modelBuilder.Entity("ERP.Models.TapDoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaTapDoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TapDoan_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTapDoan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TapDoans");
                });

            modelBuilder.Entity("ERP.Models.Translate", b =>
                {
                    b.Property<string>("Text")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZH_TW")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Text");

                    b.ToTable("Translates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ERP.Data.MyDbContext+ApplicationUserRole", b =>
                {
                    b.HasOne("ERP.Data.MyDbContext+ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Models.BoPhan", b =>
                {
                    b.HasOne("ERP.Models.Phongban", "Phongban")
                        .WithMany("BoPhans")
                        .HasForeignKey("PhongBan_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Phongban");
                });

            modelBuilder.Entity("ERP.Models.CBNV_DieuChuyen", b =>
                {
                    b.HasOne("ERP.Models.DieuChuyenNhanVien", "DieuChuyenNhanVien")
                        .WithMany("cBNVDieuChuyens")
                        .HasForeignKey("DieuChuyenNhanVien_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DonVi", "DonViTraLuong")
                        .WithMany()
                        .HasForeignKey("DonViTraLuongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DonVi", "DonViTraLuongNew")
                        .WithMany()
                        .HasForeignKey("DonViTraLuongNewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DieuChuyenNhanVien");

                    b.Navigation("DonViTraLuong");

                    b.Navigation("DonViTraLuongNew");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Models.DM_BoPhan", b =>
                {
                    b.HasOne("ERP.Models.DM_DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonVi_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("ERP.Models.DM_Loai", b =>
                {
                    b.HasOne("ERP.Models.DM_Nhom", "DM_Nhom")
                        .WithMany()
                        .HasForeignKey("Nhom_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_Nhom");
                });

            modelBuilder.Entity("ERP.Models.DS_PhuongTien", b =>
                {
                    b.HasOne("ERP.Models.DM_DonVi", "DM_DonVi")
                        .WithMany()
                        .HasForeignKey("DonVi_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DM_Loai", "DM_Loai")
                        .WithMany()
                        .HasForeignKey("LoaiPT_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DM_Model", "DM_Model")
                        .WithMany()
                        .HasForeignKey("Model_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DM_TinhTrang", "DM_TinhTrang")
                        .WithMany()
                        .HasForeignKey("TinhTrang_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_DonVi");

                    b.Navigation("DM_Loai");

                    b.Navigation("DM_Model");

                    b.Navigation("DM_TinhTrang");
                });

            modelBuilder.Entity("ERP.Models.DS_ThietBi", b =>
                {
                    b.HasOne("ERP.Models.DM_Loai", "DM_Loai")
                        .WithMany()
                        .HasForeignKey("LoaiTB_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DM_Model", "DM_Model")
                        .WithMany()
                        .HasForeignKey("Model_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_Loai");

                    b.Navigation("DM_Model");
                });

            modelBuilder.Entity("ERP.Models.DieuChuyenNhanVien", b =>
                {
                    b.HasOne("ERP.Models.BoPhan", "BoPhan")
                        .WithMany()
                        .HasForeignKey("BoPhanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.BoPhan", "BoPhanNew")
                        .WithMany()
                        .HasForeignKey("BoPhanNewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.ChucVu", "ChucVuNew")
                        .WithMany()
                        .HasForeignKey("ChucVuNewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DonVi", "DonViNew")
                        .WithMany()
                        .HasForeignKey("DonViNewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.Phongban", "Phongban")
                        .WithMany()
                        .HasForeignKey("PhongbanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.Phongban", "PhongbanNew")
                        .WithMany()
                        .HasForeignKey("PhongbanNewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BoPhan");

                    b.Navigation("BoPhanNew");

                    b.Navigation("ChucVu");

                    b.Navigation("ChucVuNew");

                    b.Navigation("DonVi");

                    b.Navigation("DonViNew");

                    b.Navigation("Phongban");

                    b.Navigation("PhongbanNew");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Models.DonVi", b =>
                {
                    b.HasOne("ERP.Models.TapDoan", "TapDoan")
                        .WithMany()
                        .HasForeignKey("TapDoan_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TapDoan");
                });

            modelBuilder.Entity("ERP.Models.KeHoachBaoDuong", b =>
                {
                    b.HasOne("ERP.Models.DM_BaoDuong", "BaoDuong")
                        .WithMany()
                        .HasForeignKey("BaoDuong_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DS_PhuongTien", "PhuongTien")
                        .WithMany()
                        .HasForeignKey("PhuongTien_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DS_ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("ThietBi_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaoDuong");

                    b.Navigation("PhuongTien");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("ERP.Models.LichSuBaoDuong", b =>
                {
                    b.HasOne("ERP.Models.DM_BaoDuong", "BaoDuong")
                        .WithMany()
                        .HasForeignKey("BaoDuong_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DS_PhuongTien", "PhuongTien")
                        .WithMany()
                        .HasForeignKey("PhuongTien_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DS_ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("ThietBi_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaoDuong");

                    b.Navigation("PhuongTien");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("ERP.Models.Log", b =>
                {
                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("AccessdBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ERP.Models.Menu_Role", b =>
                {
                    b.HasOne("ERP.Models.Menu", "Menu")
                        .WithMany("Menu_Roles")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Data.MyDbContext+ApplicationRole", "Role")
                        .WithMany("Menu_Roles")
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Models.Phongban", b =>
                {
                    b.HasOne("ERP.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonVi_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("ERP.Models.PhuongTien_DonVi", b =>
                {
                    b.HasOne("ERP.Models.DM_BoPhan", "BoPhan")
                        .WithMany()
                        .HasForeignKey("BoPhan_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DM_DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonVi_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DS_PhuongTien", "PhuongTien")
                        .WithMany()
                        .HasForeignKey("PhuongTien_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BoPhan");

                    b.Navigation("DonVi");

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("ERP.Models.PhuongTien_PhuTrach", b =>
                {
                    b.HasOne("ERP.Models.DS_PhuongTien", "PhuongTien")
                        .WithMany()
                        .HasForeignKey("PhuongTien_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhuongTien");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Models.RoleByDonVi", b =>
                {
                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Models.Role_DV_PB", b =>
                {
                    b.HasOne("ERP.Models.BoPhan", "BoPhan")
                        .WithMany()
                        .HasForeignKey("BoPhan_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonVi_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.Phongban", "Phongban")
                        .WithMany()
                        .HasForeignKey("Phongban_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.RoleByDonVi", "RoleByDonVi")
                        .WithMany("Role_DV_PBs")
                        .HasForeignKey("RoleByDonVi_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.TapDoan", "TapDoan")
                        .WithMany()
                        .HasForeignKey("TapDoan_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BoPhan");

                    b.Navigation("DonVi");

                    b.Navigation("Phongban");

                    b.Navigation("RoleByDonVi");

                    b.Navigation("TapDoan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ERP.Data.MyDbContext+ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ERP.Data.MyDbContext+ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Data.MyDbContext+ApplicationRole", b =>
                {
                    b.Navigation("Menu_Roles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ERP.Data.MyDbContext+ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ERP.Models.DieuChuyenNhanVien", b =>
                {
                    b.Navigation("cBNVDieuChuyens");
                });

            modelBuilder.Entity("ERP.Models.Menu", b =>
                {
                    b.Navigation("Menu_Roles");
                });

            modelBuilder.Entity("ERP.Models.Phongban", b =>
                {
                    b.Navigation("BoPhans");
                });

            modelBuilder.Entity("ERP.Models.RoleByDonVi", b =>
                {
                    b.Navigation("Role_DV_PBs");
                });
#pragma warning restore 612, 618
        }
    }
}
